// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		double random_num;
		int biggerThanHalf = 0;
		int smallerThanHalf = 0;
		int N = Integer.parseInt(args[0]);
		while(N>0){
			random_num = Math.random();
			//System.out.println(random_num);
			if (random_num>0.5) {biggerThanHalf++;}else{smallerThanHalf++;}
			//System.out.println(biggerThanHalf);
			//System.out.println(smallerThanHalf);

			N--;
		}
		double ratio;
		if(biggerThanHalf >0 & smallerThanHalf > 0){ratio = (double)biggerThanHalf / (double)smallerThanHalf;}else{ratio=0;}
		System.out.println("> 0.5: " + biggerThanHalf + " times");
		System.out.println("<= 0.5: " + smallerThanHalf+ " times");
		System.out.println("Ratio: " + ratio);
		


	    // Replace this comment with your code
	}
}
